# Generated by Django 6.1 on 2026-09-01 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0001_initial'),
        ('sales', '0002_alter_salereturn_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='total_installments',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='number_of_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='installmentplan',
            table=None,
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='installments.installmentplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
